services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - URL=https://outline.ozeliurs.com
      - DATABASE_URL=postgres://user:pass@localhost:5432/outline
      - REDIS_URL=redis://localhost:6379
      - FILE_STORAGE=local
      - FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
      - FILE_STORAGE_UPLOAD_MAX_SIZE=262144000
    volumes:
      - ./outline/app:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.outline.rule=Host(`outline.ozeliurs.com`)"
      - "traefik.http.routers.outline.entrypoints=websecure"
      - "traefik.http.services.outline.loadbalancer.server.port=3000"
      - "traefik.http.routers.outline.tls=true"
      - "traefik.http.routers.outline.tls.certresolver=cloudflare"

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

  postgres:
    image: postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - ./outline/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "outline", "-U", "user" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

volumes:
  storage-data:
  database-data:

networks:
  traefik:
    external: true